# Generated by Django 5.2.5 on 2025-09-06 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='organizations', to='techstack.technology')),
                ('topics', models.ManyToManyField(blank=True, related_name='organizations', to='techstack.topic')),
            ],
        ),
    ]
