# Generated by Django 5.2.5 on 2025-09-06 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='projects_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('project_code_url', models.URLField(blank=True, null=True)),
                ('mentors', models.ManyToManyField(blank=True, related_name='projects', to='organizations.mentor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.program')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='techstack.technology')),
                ('topics', models.ManyToManyField(blank=True, related_name='projects', to='techstack.topic')),
            ],
        ),
    ]
