
technologies =[
    "React", "Angular", "Vue.js", "Svelte", "Preact", "Ember.js", "Backbone.js",
    "jQuery", "SolidJS", "Qwik", "Alpine.js", "Bootstrap", "Tailwind CSS",
    "Materialize", "Foundation", "Bulma", "Sass", "Less", "Stylus", "PostCSS",
    "Redux", "MobX", "Vuex", "Zustand", "Recoil", "Pinia", "Webpack", "Vite",
    "Parcel", "Rollup", "Gulp", "Grunt", "esbuild", "Babel", "WebAssembly",
    "Blazor", "Handlebars", "Pug", "EJS", "Jinja2", "Next.js", "Gatsby",
    "Nuxt.js", "Hugo", "Jekyll", "Eleventy", "Astro", "Jest", "Mocha", "Chai",
    "Jasmine", "Cypress", "Playwright", "Storybook", "React Testing Library",
    "HTML5", "CSS3", "JavaScript (ES6+)", "TypeScript", "D3.js", "Three.js",
    "PWA (Progressive Web Apps)", "WebSockets", "WebRTC",
    "Django", "Flask", "FastAPI", "Tornado", "Sanic", "Node.js", "Express.js",
    "Koa", "NestJS", "Hapi", "Spring Boot", "Jakarta EE", "Play Framework",
    "Micronaut", "Quarkus", "ASP.NET Core", ".NET Framework", "Ruby on Rails",
    "Sinatra", "Laravel", "Symfony", "CodeIgniter", "Gin", "Echo", "Actix",
    "Rocket", "Phoenix", "Nginx", "Apache HTTP Server", "Caddy",
    "IIS (Internet Information Services)", "RESTful APIs", "GraphQL", "gRPC",
    "Message Queues (RabbitMQ, Kafka, SQS)", "SOAP", "AWS Lambda",
    "Google Cloud Functions", "Azure Functions", "Vercel Functions",
    "Netlify Functions", "OAuth 2.0", "OpenID Connect (OIDC)",
    "JWT (JSON Web Tokens)", "SAML", "Redis", "Memcached",
    "PostgreSQL", "MySQL", "MariaDB", "Microsoft SQL Server", "Oracle Database",
    "SQLite", "CockroachDB", "TiDB", "MongoDB", "CouchDB", "Firestore",
    "DynamoDB", "Riak", "etcd", "Apache Cassandra", "HBase", "Neo4j", "ArangoDB",
    "Amazon Neptune", "Elasticsearch", "OpenSearch", "Algolia", "MeiliSearch",
    "Typesense", "InfluxDB", "TimescaleDB", "Prometheus", "Google Spanner",
    "YugabyteDB", "VoltDB", "Pinecone", "Weaviate", "Milvus", "Chroma", "Qdrant",
    "SQLAlchemy (Python)", "Django ORM (Python)", "TypeORM (TypeScript/JavaScript)",
    "Prisma (TypeScript/JavaScript)", "Hibernate (Java)",
    "Entity Framework Core (C#)", "GORM (Go)", "Active Record (Ruby)",
    "Python", "JavaScript", "Java", "C#", "C++", "C", "Go", "Ruby", "PHP",
    "Swift", "Kotlin", "Rust", "Scala", "Perl", "Lua", "Haskell", "Elixir",
    "Erlang", "Clojure", "F#", "Dart", "R", "Julia", "OCaml", "Groovy", "Lisp",
    "Scheme", "Objective-C", "Assembly", "Zig", "SQL", "HTML", "CSS", "Bash",
    "PowerShell", "MATLAB", "Solidity",
    "Git", "GitHub", "GitLab", "Bitbucket", "Subversion (SVN)", "Docker",
    "Kubernetes", "Podman", "Docker Swarm", "OpenShift", "Nomad", "Jenkins",
    "GitHub Actions", "GitLab CI/CD", "CircleCI", "Travis CI", "TeamCity",
    "Argo CD", "Flux", "Amazon Web Services (AWS)", "Google Cloud Platform (GCP)",
    "Microsoft Azure", "Heroku", "DigitalOcean", "Vercel", "Netlify",
    "Terraform", "Ansible", "Pulumi", "Chef", "Puppet", "AWS CloudFormation",
    "Grafana", "Datadog", "New Relic", "Splunk",
    "ELK Stack (Elasticsearch, Logstash, Kibana)", "Jaeger", "Zipkin",
    "Visual Studio Code (VS Code)", "JetBrains IDEs (IntelliJ IDEA, PyCharm, WebStorm, etc.)",
    "Visual Studio", "Sublime Text", "Atom", "Vim", "Neovim", "Emacs",
    "Jira", "Confluence", "Trello", "Asana", "Slack", "Microsoft Teams",
    "Notion", "Postman", "Insomnia", "Swagger / OpenAPI",
    "npm (Node.js)", "Yarn (Node.js)", "pnpm (Node.js)", "pip (Python)",
    "Maven (Java)", "Gradle (Java)", "NuGet (C#)", "Composer (PHP)",
    "RubyGems (Ruby)", "Cargo (Rust)", "Homebrew (macOS)"
]
